# Generated by Django 5.1.1 on 2024-10-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("books", "0001_initial"), ("books", "0002_alter_book_cover")]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "cover",
                    models.CharField(
                        choices=[("HARD COVER", "HARD"), ("SOFT COVER", "SOFT")],
                        max_length=10,
                    ),
                ),
                ("inventory", models.PositiveIntegerField()),
                ("daily_fee", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
